name = "cloudflare-image-stabilizer-sample"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2022-03-09"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
